export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  CODE_INVALID = 'CODE_INVALID',
  CANT_DELETE_USER_ADMIN = 'CANT_DELETE_USER_ADMIN',
  DONT_HAVE_PERMISSION = 'DONT_HAVE_PERMISSION',
  IS_NOT_ADMIN = 'IS_NOT_ADMIN',
  ADMIN_ROLE_CANNOT_BE_DELETED = 'ADMIN_ROLE_CANNOT_BE_DELETED',
  DEFAULT_ROLE_CANNOT_BE_DELETED = 'DEFAULT_ROLE_CANNOT_BE_DELETED',
}
